const items = [
    {
        id: 1,
        name: 'Lake In Yosemite',
        img: '01',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 36,
        tags: ['yosemite', 'lake', 'nature', 'landscape', 'usa', 'mountains', 'snow']
    },
    {
        id: 2,
        name: 'Stars Above Yosemite',
        img: '02',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 28,
        tags: ['stars', 'sky']
    },
    {
        id: 3,
        name: 'Mountains In Yosemite',
        img: '03',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 46,
        tags: ['yosemite', 'lake', 'nature', 'landscape', 'usa', 'mountains', 'snow']
    },
    {
        id: 4,
        name: 'Half Dome - Yosemite',
        img: '04',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 22,
        tags: ['yosemite', 'nature', 'landscape', 'usa', 'mountains', 'snow']
    },
    {
        id: 5,
        name: 'El Capitan - Yosemite',
        img: '05',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['yosemite', 'nature', 'landscape', 'usa', 'mountains', 'trees']
    },
    {
        id: 6,
        name: 'Yosemite Valley',
        img: '06',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 33,
        tags: ['yosemite', 'nature', 'landscape', 'usa', 'mountains', 'trees']
    },
    {
        id: 7,
        name: 'Hit The Road',
        img: '07',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 12,
        tags: ['nature', 'landscape', 'trees', 'road']
    },
    {
        id: 8,
        name: 'Golden Gate Bridge At Dusk',
        img: '08',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 65,
        tags: ['usa', 'San Francisco', 'sea', 'bridge', 'urban', 'architecture']
    },
    {
        id: 9,
        name: 'Half Dome At Night',
        img: '09',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 41,
        tags: ['yosemite', 'nature', 'landscape', 'usa', 'mountains', 'trees', 'night', 'stars']
    },
    {
        id: 10,
        name: 'Golden Gate Bridge',
        img: '10',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 37,
        tags: ['usa', 'San Francisco', 'sea', 'bridge', 'urban', 'architecture']
    },
    {
        id: 11,
        name: 'Late Evening In Yosemite',
        img: '11',
        author: 'Casey Horner',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['yosemite', 'nature', 'landscape', 'usa', 'mountains', 'trees']
    },
    {
        id: 12,
        name: 'Rocks In The Sea',
        img: '12',
        author: 'Erik Odiin',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['sea', 'nature', 'landscape', 'drone']
    },
    {
        id: 13,
        name: 'Castle In Dusk',
        img: '13',
        author: 'Erik Odiin',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['castle']
    },
    {
        id: 14,
        name: 'Lake From The Above',
        img: '14',
        author: 'Erik Odiin',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['lake', 'nature', 'landscape', 'drone', 'snow', 'trees']
    },
    {
        id: 15,
        name: 'Shipping Containers',
        img: '15',
        author: 'Erik Odiin',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['60 x 40', '80 x 60', '100 x 75', '120 x 90'],
        format: 'landscape',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['drone', 'urban', 'industrial']
    },
    {
        id: 16,
        name: 'Sunrise In Mountains',
        img: '16',
        author: 'Erik Odiin',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['mountains', 'nature', 'landscape', 'snow', 'trees']
    },
    {
        id: 17,
        name: 'Night In Mountains',
        img: '17',
        author: 'Erik Odiin',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['mountains', 'nature', 'landscape', 'snow', 'trees', 'drone', 'night']
    },
    {
        id: 18,
        name: 'Stairway To Heaven',
        img: '18',
        author: 'Fahrul Azmi',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['urban', 'lights', 'night', 'architecture']
    },
    {
        id: 19,
        name: 'Highway At Night',
        img: '19',
        author: 'Fahrul Azmi',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['urban', 'road', 'night', 'drone']
    },
    {
        id: 20,
        name: 'Mosque At Night',
        img: '20',
        author: 'Fahrul Azmi',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['urban', 'architecture', 'night']
    },
    {
        id: 21,
        name: 'Two Boats',
        img: '21',
        author: 'Fahrul Azmi',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['sea', 'boat', 'drone']
    },
    {
        id: 22,
        name: 'Mosque From The Above',
        img: '22',
        author: 'Fahrul Azmi',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['urban', 'architecture', 'drone']
    },
    {
        id: 23,
        name: 'Just A Building',
        img: '23',
        author: 'Fahrul Azmi',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['urban', 'architecture']
    },
    {
        id: 24,
        name: 'Highway And Sea',
        img: '24',
        author: 'Fahrul Azmi',
        thickness: [12,18,24],
        finish: ['glossy', 'matte', 'satin', 'metallic'],
        sizes: ['40 x 65', '50 x 75', '60 x 90', '80 x 120'],
        format: 'portrait',
        pricing: [39.99, 68.99, 94.99],
        sold: 18,
        tags: ['urban', 'road', 'drone']
    },
];

export default items;